#!/bin/bash

if [ ! -f "${HOME}/.config/gzdoom/gzdoom.ini" ]; then
  mkdir -p "${HOME}/.config/gzdoom"
  cp \
    /defaults/gzdoom.ini \
    "${HOME}/.config/gzdoom/gzdoom.ini"
fi


# Run BOA
foot -e /usr/games/gzdoom -iwad wolf_boa.ipk3
