#!/bin/bash

# default file copies first run
if [ ! -f $HOME/.config/tint2/tint2rc ]; then
    mkdir -p $HOME/.config/tint2
    cp /defaults/tint2rc $HOME/.config/tint2/tint2rc
fi

# Handle file opening
ARGS=()
if [ -n "$SEALSKIN_FILE" ]; then
    ARGS+=("$SEALSKIN_FILE")
fi

# Start UI
tint2 &
calligra "${ARGS[@]}"
