#!/bin/bash

if [ ! -f "${HOME}/.config/gzdoom/gzdoom.ini" ]; then
  mkdir -p "${HOME}/.config/gzdoom"
  cp \
    /defaults/gzdoom.ini \
    "${HOME}/.config/gzdoom/gzdoom.ini"
  cp \
    /defaults/freedoom1.wad \
    "${HOME}/Desktop/"
fi

# Run GZDoom
xterm -e /usr/games/gzdoom $SEALSKIN_FILE $SEALSKIN_URL
