#!/bin/bash

# Copy default config
if [ ! -f "${HOME}/.mame/mame.ini" ]; then
  mkdir -p "${HOME}/.mame"
  cp \
    /defaults/mame.ini \
    "${HOME}/.mame/mame.ini"
fi

# Run MAME
xterm -e /usr/games/mame "$SEALSKIN_FILE" "$SEALSKIN_URL"
