#!/bin/bash

# Copy default config
if [ ! -f "${HOME}/.mame/mame.ini" ]; then
  mkdir -p "${HOME}/.mame"
  cp \
    /defaults/mame.ini \
    "${HOME}/.mame/mame.ini"
fi

# Handle file opening
ARGS=()
if [ -n "$SEALSKIN_FILE" ]; then
    ROM_NAME=$(basename "$SEALSKIN_FILE")
    ROM_NAME="${ROM_NAME%.*}"
    ARGS+=("$ROM_NAME")
fi

# Run MAME
xterm -e /usr/games/mame "${ARGS[@]}"
